update for 2018

diff --git a/bin/cronjob b/bin/cronjob
--- a/bin/cronjob
+++ b/bin/cronjob
@@ -1,80 +1,257 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
-#!/bin/bash
+set -euo pipefail
 
-#!/bin/bash
+##bash-libs: out.sh @ 33fa96d5 (1.1.6)
 
-export CDEF="[0m"
-export CRED="[31m"
-export CGRN="[32m"
-export CYEL="[33m"
-export CBLU="[34m"
-export CBRED="[1;31m"
-export CBGRN="[1;32m"
-export CBYEL="[1;33m"
-export CBBLU="[1;34m"
+##bash-libs: colours.sh @ 33fa96d5 (1.1.6)
 
-MODE_DEBUG=no
-
-### debuge MESSAGE Usage:bbuild
-# print a blue debug message to stderr
-# only prints if MODE_DEBUG is set to "yes"
+### Colours for bash Usage:bbuild
+# A series of colour flags for use in outputs.
+#
+# Example:
+# 	
+# 	echo -e "${CRED}Some red text ${CBBLU} some blue text $CDEF some text in the terminal's default colour")
+#
+# Requires processing of escape characters.
+#
+# Colours available:
+#
+# CRED, CBRED, HLRED -- red, bold red, highlight red
+# CGRN, CBGRN, HLGRN -- green, bold green, highlight green
+# CYEL, CBYEL, HLYEL -- yellow, bold yellow, highlight yellow
+# CBLU, CBBLU, HLBLU -- blue, bold blue, highlight blue
+# CPUR, CBPUR, HLPUR -- purple, bold purple, highlight purple
+# CTEA, CBTEA, HLTEA -- teal, bold teal, highlight teal
+#
+# CDEF -- switches to the terminal default
+# CUNL -- add underline
+#
+# Note that highlight and underline must be applied or re-applied after specifying a colour.
+#
+# If the session is detected as being in a pipe, colours will be turned off.
+#   You can override this by calling `colours:check --color=always` at the start of your script
+#
 ###/doc
-function debuge {
-	if [[ "$MODE_DEBUG" = yes ]]; then
-		echo -e "${CBBLU}DEBUG:$CBLU$*$CDEF" 1>&2
-	fi
+
+##bash-libs: tty.sh @ 33fa96d5 (1.1.6)
+
+tty:is_ssh() {
+    [[ -n "$SSH_TTY" ]] || [[ -n "$SSH_CLIENT" ]] || [[ "$SSH_CONNECTION" ]]
 }
 
-### infoe MESSAGE Usage:bbuild
+tty:is_pipe() {
+    [[ ! -t 1 ]]
+}
+
+### colours:check ARGS Usage:bbuild
+#
+# Check the args to see if there's a `--color=always` or `--color=never`
+#   and reload the colours appropriately
+#
+###/doc
+colours:check() {
+    if [[ "$*" =~ --color=always ]]; then
+        COLOURS_ON=true
+    elif [[ "$*" =~ --color=never ]]; then
+        COLOURS_ON=false
+    fi
+
+    colours:define
+    return 0
+}
+
+colours:auto() {
+    if tty:is_pipe ; then
+        COLOURS_ON=false
+    else
+        COLOURS_ON=true
+    fi
+
+    colours:define
+    return 0
+}
+
+colours:define() {
+    if [[ "$COLOURS_ON" = false ]]; then
+
+        export CRED=''
+        export CGRN=''
+        export CYEL=''
+        export CBLU=''
+        export CPUR=''
+        export CTEA=''
+
+        export CBRED=''
+        export CBGRN=''
+        export CBYEL=''
+        export CBBLU=''
+        export CBPUR=''
+        export CBTEA=''
+
+        export HLRED=''
+        export HLGRN=''
+        export HLYEL=''
+        export HLBLU=''
+        export HLPUR=''
+        export HLTEA=''
+
+        export CDEF=''
+
+    else
+
+        export CRED=$(echo -e "\033[0;31m")
+        export CGRN=$(echo -e "\033[0;32m")
+        export CYEL=$(echo -e "\033[0;33m")
+        export CBLU=$(echo -e "\033[0;34m")
+        export CPUR=$(echo -e "\033[0;35m")
+        export CTEA=$(echo -e "\033[0;36m")
+
+        export CBRED=$(echo -e "\033[1;31m")
+        export CBGRN=$(echo -e "\033[1;32m")
+        export CBYEL=$(echo -e "\033[1;33m")
+        export CBBLU=$(echo -e "\033[1;34m")
+        export CBPUR=$(echo -e "\033[1;35m")
+        export CBTEA=$(echo -e "\033[1;36m")
+
+        export HLRED=$(echo -e "\033[41m")
+        export HLGRN=$(echo -e "\033[42m")
+        export HLYEL=$(echo -e "\033[43m")
+        export HLBLU=$(echo -e "\033[44m")
+        export HLPUR=$(echo -e "\033[45m")
+        export HLTEA=$(echo -e "\033[46m")
+
+        export CDEF=$(echo -e "\033[0m")
+
+    fi
+}
+
+colours:auto
+
+### Console output handlers Usage:bbuild
+#
+# Write data to console stderr using colouring
+#
+###/doc
+
+### out:info MESSAGE Usage:bbuild
 # print a green informational message to stderr
 ###/doc
-function infoe {
-	echo -e "$CGRN$*$CDEF" 1>&2
+function out:info {
+    echo "$CGRN$*$CDEF" 1>&2
 }
 
-### warne MESSAGE Usage:bbuild
+### out:warn MESSAGE Usage:bbuild
 # print a yellow warning message to stderr
 ###/doc
-function warne {
-	echo -e "${CBYEL}WARN:$CYEL $*$CDEF" 1>&2
+function out:warn {
+    echo "${CBYEL}WARN: $CYEL$*$CDEF" 1>&2
 }
 
-### faile MESSAGE CODE Usage:bbuild
+### out:defer MESSAGE Usage:bbuild
+# Store a message in the output buffer for later use
+###/doc
+function out:defer {
+    OUTPUT_BUFFER_defer[${#OUTPUT_BUFFER_defer[@]}]="$*"
+}
+
+# Internal
+function out:buffer_initialize {
+    OUTPUT_BUFFER_defer=(:)
+}
+out:buffer_initialize
+
+### out:flush HANDLER ... Usage:bbuild
+#
+# Pass the output buffer to the command defined by HANDLER
+# and empty the buffer
+#
+# Examples:
+#
+# 	out:flush echo -e
+#
+# 	out:flush out:warn
+#
+# (escaped newlines are added in the buffer, so `-e` option is
+#  needed to process the escape sequences)
+#
+###/doc
+function out:flush {
+    [[ -n "$*" ]] || out:fail "Did not provide a command for buffered output\n\n${OUTPUT_BUFFER_defer[*]}"
+
+    [[ "${#OUTPUT_BUFFER_defer[@]}" -gt 1 ]] || return 0
+
+    for buffer_line in "${OUTPUT_BUFFER_defer[@]:1}"; do
+        "$@" "$buffer_line"
+    done
+
+    out:buffer_initialize
+}
+
+### out:fail [CODE] MESSAGE Usage:bbuild
 # print a red failure message to stderr and exit with CODE
 # CODE must be a number
 # if no code is specified, error code 127 is used
 ###/doc
-function faile {
-	local MSG=
-	local ARG=
-	local ERCODE=127
-	local numpat='^[0-9]+$'
-	while [[ -n "$*" ]]; do
-		ARG=$1 ; shift
-		if [[ -z "$*" ]] && [[ "$ARG" =~ $numpat ]]; then
-			ERCODE=$ARG
-		else
-			MSG="$MSG $ARG"
-		fi
-	done
-	echo "${CBRED}ERROR FAIL:$CRED$MSG$CDEF" 1>&2
-	exit "$ERCODE"
+function out:fail {
+    local ERCODE=127
+    local numpat='^[0-9]+$'
+
+    if [[ "$1" =~ $numpat ]]; then
+        ERCODE="$1"; shift || :
+    fi
+
+    echo "${CBRED}ERROR FAIL: $CRED$*$CDEF" 1>&2
+    exit $ERCODE
 }
 
-function dumpe {
-	echo -n "[1;35m$*" 1>&2
-	echo -n "[0;35m" 1>&2
-	cat - 1>&2
-	echo -n "[0m" 1>&2
+### out:error MESSAGE Usage:bbuild
+# print a red error message to stderr
+#
+# unlike out:fail, does not cause script exit
+###/doc
+function out:error {
+    echo "${CBRED}ERROR: ${CRED}$*$CDEF" 1>&2
+}
+##bash-libs: isroot.sh @ 33fa96d5 (1.1.6)
+
+
+### isroot Usage:bbuild
+# Test for root access
+#
+# If using cygwin, user is always root.
+###/doc
+
+function isroot {
+    [[ "$UID" = 0 ]] || isroot:cygwin
 }
 
-if [[ "$*" =~ --debug ]]; then
-	MODE_DEBUG=yes
-fi
+### isroot:cygwin Usage:bbuild
+# Returns whether running under cygwin.
+#
+# Typically a user under cygwin is root, except when they're not
+#
+# This utility exists as a reminder to check for cygwin.
+###/doc
 
-if [[ "$UID" -gt 0 ]]; then faile Must be root
-fi
+function isroot:cygwin {
+    uname -o | grep -i cygwin -q
+}
 
-cd "/root/partimus-updater"
+### isroot:require MESSAGE Usage:bbuild
+# Require root. If script is not running as root,
+# print message and exit
+###/doc
+function isroot:require {
+    isroot || out:fail "$*"
+}
+
+PUP_conf=/etc/partimus/updater.conf
+PUP_logfile=/var/log/partimus/updater.log
+PUP_gitdir=/root/partimus-updater
+
+isroot:require "You must be root to run the updater job"
+
+cd "$PUP_gitdir"
+
 bin/pupdater >/dev/null 2>&1
diff --git a/bin/pupdater b/bin/pupdater
--- a/bin/pupdater
+++ b/bin/pupdater
@@ -1,109 +1,352 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
 set -euo pipefail
 
-#!/bin/bash
+##bash-libs: out.sh @ 33fa96d5 (1.1.6)
 
-#!/bin/bash
+##bash-libs: colours.sh @ 33fa96d5 (1.1.6)
 
-export CDEF="[0m"
-export CRED="[31m"
-export CGRN="[32m"
-export CYEL="[33m"
-export CBLU="[34m"
-export CBRED="[1;31m"
-export CBGRN="[1;32m"
-export CBYEL="[1;33m"
-export CBBLU="[1;34m"
-
-MODE_DEBUG=no
-
-### debuge MESSAGE Usage:bbuild
-# print a blue debug message to stderr
-# only prints if MODE_DEBUG is set to "yes"
+### Colours for bash Usage:bbuild
+# A series of colour flags for use in outputs.
+#
+# Example:
+# 	
+# 	echo -e "${CRED}Some red text ${CBBLU} some blue text $CDEF some text in the terminal's default colour")
+#
+# Requires processing of escape characters.
+#
+# Colours available:
+#
+# CRED, CBRED, HLRED -- red, bold red, highlight red
+# CGRN, CBGRN, HLGRN -- green, bold green, highlight green
+# CYEL, CBYEL, HLYEL -- yellow, bold yellow, highlight yellow
+# CBLU, CBBLU, HLBLU -- blue, bold blue, highlight blue
+# CPUR, CBPUR, HLPUR -- purple, bold purple, highlight purple
+# CTEA, CBTEA, HLTEA -- teal, bold teal, highlight teal
+#
+# CDEF -- switches to the terminal default
+# CUNL -- add underline
+#
+# Note that highlight and underline must be applied or re-applied after specifying a colour.
+#
+# If the session is detected as being in a pipe, colours will be turned off.
+#   You can override this by calling `colours:check --color=always` at the start of your script
+#
 ###/doc
-function debuge {
-	if [[ "$MODE_DEBUG" = yes ]]; then
-		echo -e "${CBBLU}DEBUG:$CBLU$*$CDEF" 1>&2
-	fi
+
+##bash-libs: tty.sh @ 33fa96d5 (1.1.6)
+
+tty:is_ssh() {
+    [[ -n "$SSH_TTY" ]] || [[ -n "$SSH_CLIENT" ]] || [[ "$SSH_CONNECTION" ]]
 }
 
-### infoe MESSAGE Usage:bbuild
+tty:is_pipe() {
+    [[ ! -t 1 ]]
+}
+
+### colours:check ARGS Usage:bbuild
+#
+# Check the args to see if there's a `--color=always` or `--color=never`
+#   and reload the colours appropriately
+#
+###/doc
+colours:check() {
+    if [[ "$*" =~ --color=always ]]; then
+        COLOURS_ON=true
+    elif [[ "$*" =~ --color=never ]]; then
+        COLOURS_ON=false
+    fi
+
+    colours:define
+    return 0
+}
+
+colours:auto() {
+    if tty:is_pipe ; then
+        COLOURS_ON=false
+    else
+        COLOURS_ON=true
+    fi
+
+    colours:define
+    return 0
+}
+
+colours:define() {
+    if [[ "$COLOURS_ON" = false ]]; then
+
+        export CRED=''
+        export CGRN=''
+        export CYEL=''
+        export CBLU=''
+        export CPUR=''
+        export CTEA=''
+
+        export CBRED=''
+        export CBGRN=''
+        export CBYEL=''
+        export CBBLU=''
+        export CBPUR=''
+        export CBTEA=''
+
+        export HLRED=''
+        export HLGRN=''
+        export HLYEL=''
+        export HLBLU=''
+        export HLPUR=''
+        export HLTEA=''
+
+        export CDEF=''
+
+    else
+
+        export CRED=$(echo -e "\033[0;31m")
+        export CGRN=$(echo -e "\033[0;32m")
+        export CYEL=$(echo -e "\033[0;33m")
+        export CBLU=$(echo -e "\033[0;34m")
+        export CPUR=$(echo -e "\033[0;35m")
+        export CTEA=$(echo -e "\033[0;36m")
+
+        export CBRED=$(echo -e "\033[1;31m")
+        export CBGRN=$(echo -e "\033[1;32m")
+        export CBYEL=$(echo -e "\033[1;33m")
+        export CBBLU=$(echo -e "\033[1;34m")
+        export CBPUR=$(echo -e "\033[1;35m")
+        export CBTEA=$(echo -e "\033[1;36m")
+
+        export HLRED=$(echo -e "\033[41m")
+        export HLGRN=$(echo -e "\033[42m")
+        export HLYEL=$(echo -e "\033[43m")
+        export HLBLU=$(echo -e "\033[44m")
+        export HLPUR=$(echo -e "\033[45m")
+        export HLTEA=$(echo -e "\033[46m")
+
+        export CDEF=$(echo -e "\033[0m")
+
+    fi
+}
+
+colours:auto
+
+### Console output handlers Usage:bbuild
+#
+# Write data to console stderr using colouring
+#
+###/doc
+
+### out:info MESSAGE Usage:bbuild
 # print a green informational message to stderr
 ###/doc
-function infoe {
-	echo -e "$CGRN$*$CDEF" 1>&2
+function out:info {
+    echo "$CGRN$*$CDEF" 1>&2
 }
 
-### warne MESSAGE Usage:bbuild
+### out:warn MESSAGE Usage:bbuild
 # print a yellow warning message to stderr
 ###/doc
-function warne {
-	echo -e "${CBYEL}WARN:$CYEL $*$CDEF" 1>&2
+function out:warn {
+    echo "${CBYEL}WARN: $CYEL$*$CDEF" 1>&2
 }
 
-### faile MESSAGE CODE Usage:bbuild
+### out:defer MESSAGE Usage:bbuild
+# Store a message in the output buffer for later use
+###/doc
+function out:defer {
+    OUTPUT_BUFFER_defer[${#OUTPUT_BUFFER_defer[@]}]="$*"
+}
+
+# Internal
+function out:buffer_initialize {
+    OUTPUT_BUFFER_defer=(:)
+}
+out:buffer_initialize
+
+### out:flush HANDLER ... Usage:bbuild
+#
+# Pass the output buffer to the command defined by HANDLER
+# and empty the buffer
+#
+# Examples:
+#
+# 	out:flush echo -e
+#
+# 	out:flush out:warn
+#
+# (escaped newlines are added in the buffer, so `-e` option is
+#  needed to process the escape sequences)
+#
+###/doc
+function out:flush {
+    [[ -n "$*" ]] || out:fail "Did not provide a command for buffered output\n\n${OUTPUT_BUFFER_defer[*]}"
+
+    [[ "${#OUTPUT_BUFFER_defer[@]}" -gt 1 ]] || return 0
+
+    for buffer_line in "${OUTPUT_BUFFER_defer[@]:1}"; do
+        "$@" "$buffer_line"
+    done
+
+    out:buffer_initialize
+}
+
+### out:fail [CODE] MESSAGE Usage:bbuild
 # print a red failure message to stderr and exit with CODE
 # CODE must be a number
 # if no code is specified, error code 127 is used
 ###/doc
-function faile {
-	local MSG=
-	local ARG=
-	local ERCODE=127
-	local numpat='^[0-9]+$'
-	while [[ -n "$*" ]]; do
-		ARG=$1 ; shift
-		if [[ -z "$*" ]] && [[ "$ARG" =~ $numpat ]]; then
-			ERCODE=$ARG
-		else
-			MSG="$MSG $ARG"
-		fi
-	done
-	echo "${CBRED}ERROR FAIL:$CRED$MSG$CDEF" 1>&2
-	exit "$ERCODE"
+function out:fail {
+    local ERCODE=127
+    local numpat='^[0-9]+$'
+
+    if [[ "$1" =~ $numpat ]]; then
+        ERCODE="$1"; shift || :
+    fi
+
+    echo "${CBRED}ERROR FAIL: $CRED$*$CDEF" 1>&2
+    exit $ERCODE
 }
 
-function dumpe {
-	echo -n "[1;35m$*" 1>&2
-	echo -n "[0;35m" 1>&2
-	cat - 1>&2
-	echo -n "[0m" 1>&2
+### out:error MESSAGE Usage:bbuild
+# print a red error message to stderr
+#
+# unlike out:fail, does not cause script exit
+###/doc
+function out:error {
+    echo "${CBRED}ERROR: ${CRED}$*$CDEF" 1>&2
+}
+##bash-libs: isroot.sh @ 33fa96d5 (1.1.6)
+
+
+### isroot Usage:bbuild
+# Test for root access
+#
+# If using cygwin, user is always root.
+###/doc
+
+function isroot {
+    [[ "$UID" = 0 ]] || isroot:cygwin
 }
 
-if [[ "$*" =~ --debug ]]; then
-	MODE_DEBUG=yes
-fi
+### isroot:cygwin Usage:bbuild
+# Returns whether running under cygwin.
+#
+# Typically a user under cygwin is root, except when they're not
+#
+# This utility exists as a reminder to check for cygwin.
+###/doc
 
-if [[ "$UID" -gt 0 ]]; then faile You must be root to run this utility
-fi
-
-function readconf {
-	label=$1; shift
-	if [[ ! -f /etc/partimus.conf ]]; then
-		echo ""|mailx -s "No configuration file on $machinename !" $alertemail
-	fi
-	echo $(grep -v -e '^#' /etc/partimus.conf |grep -e "^$label=" | sed "s/$label=//" )
+function isroot:cygwin {
+    uname -o | grep -i cygwin -q
 }
 
-thedate=$(date "+%F%T"|sed -r 's/[^0-9]+//g')
-alertemail=$(readconf EMAIL)
-machinename=$(readconf MACHINE)
-updatemode=$(readconf UMODE)
-logfile=/root/updater-$thedate.log
+### isroot:require MESSAGE Usage:bbuild
+# Require root. If script is not running as root,
+# print message and exit
+###/doc
+function isroot:require {
+    isroot || out:fail "$*"
+}
+##bash-libs: readkv.sh @ 33fa96d5 (1.1.6)
 
-cd /root/partimus-updater
+### Key Value Pair Reader Usage:bbuild
+#
+# Read a value given the key, from a specified file
+#
+###/doc
 
-git pull origin master || {
-	echo ""|mailx -s "Failed to pull update automation on $machinename" $alertemail
-	exit 127
+### readkv KEY FILE [DEFAULT] Usage:bbuild
+#
+# The KEY is the key in the file. A key is identified as starting at the beginning of a line, and ending at the first '=' character
+#
+# The value starts immediately after the first '=' character.
+#
+# If no value is found, the DEFAULT value is returned, or an empty string
+#
+###/doc
+
+function readkv {
+    local thedefault thekey thefile
+    thekey="$1" ; shift
+    thefile="$1"; shift
+
+    if [[ -n "${1:-}" ]]; then
+        thedefault="$1"; shift || :
+    fi
+
+    local res="$(readkv:meaningful_data "$thefile"|egrep "^$thekey"'\s*='|sed -r "s/^$thekey"'\s*=\s*//')"
+    if [[ -z "$res" ]]; then
+        echo "${thedefault:-}"
+    else
+        echo "$res"
+    fi
 }
 
-for runscript in $(find scripts/ -executable|tail -n +2 | sort ); do
-	"$runscript" >> "$logfile" || {
-		cat "$logfile"| mailx -s "[$runscript] on $machinename FAILED" $alertemail
-		if [[ "$updatemode" = "blocking" ]]; then
-			exit 2
-		fi
-	}
-done
+### readkv:require KEY FILE Usage:bbuild
+#
+# Like readkv, but causes a failure if the file does not exist.
+#
+###/doc
+
+function readkv:require {
+    if [[ -z "${2:-}" ]]; then
+        out:fail "No file specified to read [$*]"
+    fi
+
+    if [[ ! -f "$2" ]] ; then
+        out:fail "No such file $2 !"
+    fi
+
+    if ! head -n 1 "$2" > /dev/null; then
+        out:fail "Could not read $2"
+    fi
+    readkv "$@"
+}
+
+### readkv:moeaningful_data FILE Usage:bbuild
+# Dump the file contents, stripping meaningless data (empty lines and comment lines)
+###/doc
+readkv:meaningful_data() {
+    grep -v -P '^\s*(#.*)?$' "$1"
+}
+
+PUP_conf=/etc/partimus/updater.conf
+PUP_logfile=/var/log/partimus/updater.log
+PUP_gitdir=/root/partimus-updater
+
+isroot:require "You must be root to run the updater"
+
+check_config_file() {
+    if [[ ! -f "$PUP_conf" ]]; then
+        out:fail "No configuration file !"
+    fi
+}
+
+run_update_scripts() {
+    for runscript in $(find scripts/ -executable|tail -n +2 | sort ); do
+        echo "$thedate" >> "$PUP_logfile"
+        "$runscript" >> "$PUP_logfile" || {
+            cat "$PUP_logfile"| mailx -s "[$runscript] on $machinename FAILED" $alertemail
+            if [[ "$updatemode" = "blocking" ]]; then
+                exit 2
+            fi
+        }
+    done
+}
+
+main() {
+    check_config_file
+
+    thedate="$(date "+%F%T"|sed -r 's/[^0-9]+//g')"
+    alertemail="$(readkv email "$PUP_conf")"
+    machinename="$(readkv machine "$PUP_conf")"
+    updatemode="$(readkv update_mode "$PUP_conf")"
+
+    cd "$PUP_gitdir"
+
+    git pull origin master || {
+        echo ""|mailx -s "Failed to pull update automation on $machinename" $alertemail
+        exit 127
+    }
+
+}
+
+main "$@"
diff --git a/src/pupdater b/src/pupdater
--- a/src/pupdater
+++ b/src/pupdater
@@ -1,38 +1,48 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
 set -euo pipefail
 
-#%include bashout
+#%include out.sh
+#%include isroot.sh
+#%include readkv.sh
 
-if [[ "$UID" -gt 0 ]]; then faile You must be root to run this utility
-fi
+#%include configuration.sh
 
-function readconf {
-	label=$1; shift
-	if [[ ! -f /etc/partimus.conf ]]; then
-		echo ""|mailx -s "No configuration file on $machinename !" $alertemail
-	fi
-	echo $(grep -v -e '^#' /etc/partimus.conf |grep -e "^$label=" | sed "s/$label=//" )
+isroot:require "You must be root to run the updater"
+
+check_config_file() {
+    if [[ ! -f "$PUP_conf" ]]; then
+        out:fail "No configuration file !"
+    fi
 }
 
-thedate=$(date "+%F%T"|sed -r 's/[^0-9]+//g')
-alertemail=$(readconf EMAIL)
-machinename=$(readconf MACHINE)
-updatemode=$(readconf UMODE)
-logfile=/root/updater-$thedate.log
-
-cd /root/partimus-updater
-
-git pull origin master || {
-	echo ""|mailx -s "Failed to pull update automation on $machinename" $alertemail
-	exit 127
+run_update_scripts() {
+    for runscript in $(find scripts/ -executable|tail -n +2 | sort ); do
+        echo "$thedate" >> "$PUP_logfile"
+        "$runscript" >> "$PUP_logfile" || {
+            cat "$PUP_logfile"| mailx -s "[$runscript] on $machinename FAILED" $alertemail
+            if [[ "$updatemode" = "blocking" ]]; then
+                exit 2
+            fi
+        }
+    done
 }
 
-for runscript in $(find scripts/ -executable|tail -n +2 | sort ); do
-	"$runscript" >> "$logfile" || {
-		cat "$logfile"| mailx -s "[$runscript] on $machinename FAILED" $alertemail
-		if [[ "$updatemode" = "blocking" ]]; then
-			exit 2
-		fi
-	}
-done
+main() {
+    check_config_file
+
+    thedate="$(date "+%F%T"|sed -r 's/[^0-9]+//g')"
+    alertemail="$(readkv email "$PUP_conf")"
+    machinename="$(readkv machine "$PUP_conf")"
+    updatemode="$(readkv update_mode "$PUP_conf")"
+
+    cd "$PUP_gitdir"
+
+    git pull origin master || {
+        echo ""|mailx -s "Failed to pull update automation on $machinename" $alertemail
+        exit 127
+    }
+
+}
+
+main "$@"
